/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreCadastroRouteImport } from './routes/pre-cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as AcessoRapidoRouteImport } from './routes/acesso-rapido'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsuariosRouteImport } from './routes/_admin.usuarios'
import { Route as AdminTurmasRouteImport } from './routes/_admin.turmas'
import { Route as AdminSegurancaRouteImport } from './routes/_admin.seguranca'
import { Route as AdminRelatoriosRouteImport } from './routes/_admin.relatorios'
import { Route as AdminPresencaRouteImport } from './routes/_admin.presenca'
import { Route as AdminPreCadastrosRouteImport } from './routes/_admin.pre-cadastros'
import { Route as AdminPainelRouteImport } from './routes/_admin.painel'
import { Route as AdminAvisosAdminRouteImport } from './routes/_admin.avisos-admin'
import { Route as AdminAlunosRouteImport } from './routes/_admin.alunos'

const PreCadastroRoute = PreCadastroRouteImport.update({
  id: '/pre-cadastro',
  path: '/pre-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRapidoRoute = AcessoRapidoRouteImport.update({
  id: '/acesso-rapido',
  path: '/acesso-rapido',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTurmasRoute = AdminTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegurancaRoute = AdminSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPresencaRoute = AdminPresencaRouteImport.update({
  id: '/presenca',
  path: '/presenca',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreCadastrosRoute = AdminPreCadastrosRouteImport.update({
  id: '/pre-cadastros',
  path: '/pre-cadastros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPainelRoute = AdminPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvisosAdminRoute = AdminAvisosAdminRouteImport.update({
  id: '/avisos-admin',
  path: '/avisos-admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-rapido': typeof AcessoRapidoRoute
  '/avisos': typeof AvisosRoute
  '/login': typeof LoginRoute
  '/pre-cadastro': typeof PreCadastroRoute
  '/alunos': typeof AdminAlunosRoute
  '/avisos-admin': typeof AdminAvisosAdminRoute
  '/painel': typeof AdminPainelRoute
  '/pre-cadastros': typeof AdminPreCadastrosRoute
  '/presenca': typeof AdminPresencaRoute
  '/relatorios': typeof AdminRelatoriosRoute
  '/seguranca': typeof AdminSegurancaRoute
  '/turmas': typeof AdminTurmasRoute
  '/usuarios': typeof AdminUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-rapido': typeof AcessoRapidoRoute
  '/avisos': typeof AvisosRoute
  '/login': typeof LoginRoute
  '/pre-cadastro': typeof PreCadastroRoute
  '/alunos': typeof AdminAlunosRoute
  '/avisos-admin': typeof AdminAvisosAdminRoute
  '/painel': typeof AdminPainelRoute
  '/pre-cadastros': typeof AdminPreCadastrosRoute
  '/presenca': typeof AdminPresencaRoute
  '/relatorios': typeof AdminRelatoriosRoute
  '/seguranca': typeof AdminSegurancaRoute
  '/turmas': typeof AdminTurmasRoute
  '/usuarios': typeof AdminUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/acesso-rapido': typeof AcessoRapidoRoute
  '/avisos': typeof AvisosRoute
  '/login': typeof LoginRoute
  '/pre-cadastro': typeof PreCadastroRoute
  '/_admin/alunos': typeof AdminAlunosRoute
  '/_admin/avisos-admin': typeof AdminAvisosAdminRoute
  '/_admin/painel': typeof AdminPainelRoute
  '/_admin/pre-cadastros': typeof AdminPreCadastrosRoute
  '/_admin/presenca': typeof AdminPresencaRoute
  '/_admin/relatorios': typeof AdminRelatoriosRoute
  '/_admin/seguranca': typeof AdminSegurancaRoute
  '/_admin/turmas': typeof AdminTurmasRoute
  '/_admin/usuarios': typeof AdminUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-rapido'
    | '/avisos'
    | '/login'
    | '/pre-cadastro'
    | '/alunos'
    | '/avisos-admin'
    | '/painel'
    | '/pre-cadastros'
    | '/presenca'
    | '/relatorios'
    | '/seguranca'
    | '/turmas'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-rapido'
    | '/avisos'
    | '/login'
    | '/pre-cadastro'
    | '/alunos'
    | '/avisos-admin'
    | '/painel'
    | '/pre-cadastros'
    | '/presenca'
    | '/relatorios'
    | '/seguranca'
    | '/turmas'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/acesso-rapido'
    | '/avisos'
    | '/login'
    | '/pre-cadastro'
    | '/_admin/alunos'
    | '/_admin/avisos-admin'
    | '/_admin/painel'
    | '/_admin/pre-cadastros'
    | '/_admin/presenca'
    | '/_admin/relatorios'
    | '/_admin/seguranca'
    | '/_admin/turmas'
    | '/_admin/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AcessoRapidoRoute: typeof AcessoRapidoRoute
  AvisosRoute: typeof AvisosRoute
  LoginRoute: typeof LoginRoute
  PreCadastroRoute: typeof PreCadastroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pre-cadastro': {
      id: '/pre-cadastro'
      path: '/pre-cadastro'
      fullPath: '/pre-cadastro'
      preLoaderRoute: typeof PreCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-rapido': {
      id: '/acesso-rapido'
      path: '/acesso-rapido'
      fullPath: '/acesso-rapido'
      preLoaderRoute: typeof AcessoRapidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/usuarios': {
      id: '/_admin/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/turmas': {
      id: '/_admin/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof AdminTurmasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seguranca': {
      id: '/_admin/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof AdminSegurancaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/relatorios': {
      id: '/_admin/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/presenca': {
      id: '/_admin/presenca'
      path: '/presenca'
      fullPath: '/presenca'
      preLoaderRoute: typeof AdminPresencaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pre-cadastros': {
      id: '/_admin/pre-cadastros'
      path: '/pre-cadastros'
      fullPath: '/pre-cadastros'
      preLoaderRoute: typeof AdminPreCadastrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/painel': {
      id: '/_admin/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AdminPainelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/avisos-admin': {
      id: '/_admin/avisos-admin'
      path: '/avisos-admin'
      fullPath: '/avisos-admin'
      preLoaderRoute: typeof AdminAvisosAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/alunos': {
      id: '/_admin/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminAvisosAdminRoute: typeof AdminAvisosAdminRoute
  AdminPainelRoute: typeof AdminPainelRoute
  AdminPreCadastrosRoute: typeof AdminPreCadastrosRoute
  AdminPresencaRoute: typeof AdminPresencaRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminSegurancaRoute: typeof AdminSegurancaRoute
  AdminTurmasRoute: typeof AdminTurmasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlunosRoute: AdminAlunosRoute,
  AdminAvisosAdminRoute: AdminAvisosAdminRoute,
  AdminPainelRoute: AdminPainelRoute,
  AdminPreCadastrosRoute: AdminPreCadastrosRoute,
  AdminPresencaRoute: AdminPresencaRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminSegurancaRoute: AdminSegurancaRoute,
  AdminTurmasRoute: AdminTurmasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AcessoRapidoRoute: AcessoRapidoRoute,
  AvisosRoute: AvisosRoute,
  LoginRoute: LoginRoute,
  PreCadastroRoute: PreCadastroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
